# Generated by Django 3.1.7 on 2021-03-09 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Branch`s name')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Address')),
                ('contact_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Number')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Course')),
                ('course_time', models.DateField()),
                ('payment', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nitc.branch', verbose_name='Filial')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nitc.course')),
            ],
        ),
        migrations.CreateModel(
            name='MFY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nitc.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('wdate', models.DateField()),
                ('phone', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=250)),
                ('passport_seria', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d')),
                ('inn', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d')),
                ('inps', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d')),
                ('diplom', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d')),
                ('turdavoy', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d')),
                ('obyektivka', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d')),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nitc.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nitc.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('contact_number', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=100)),
                ('course_days', models.CharField(max_length=100)),
                ('course_time_type', models.CharField(max_length=100)),
                ('tolov', models.CharField(blank=True, max_length=10, null=True)),
                ('subject', models.CharField(max_length=100)),
                ('social_state', models.CharField(max_length=50)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nitc.branch')),
                ('mfy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nitc.mfy')),
                ('number_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nitc.course_part')),
                ('teacher', models.ManyToManyField(to='nitc.Teacher')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ro`yxatga olish',
                'verbose_name_plural': 'Ro`yxatdan O`tganlar',
            },
        ),
        migrations.AddField(
            model_name='mfy',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nitc.sector'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nitc.teacher'),
        ),
    ]
