# Generated by Django 3.1.7 on 2021-03-09 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nitc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(to='nitc.Teacher'),
        ),
        migrations.RemoveField(
            model_name='register',
            name='teacher',
        ),
        migrations.AddField(
            model_name='register',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nitc.teacher'),
            preserve_default=False,
        ),
    ]
