# Generated by Django 3.1.7 on 2021-03-09 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nitc', '0002_auto_20210309_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nitc.course'),
        ),
    ]
