# Generated by Django 3.1.7 on 2021-03-09 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nitc', '0003_auto_20210309_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='mfy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nitc.mfy'),
        ),
    ]
