# Generated by Django 3.1.7 on 2021-03-09 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nitc', '0004_auto_20210309_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nitc.teacher'),
        ),
    ]
